# Generated by Django 5.2.12 on 2026-04-07 12:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('repayment_months', models.IntegerField(default=1)),
                ('monthly_installment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted')], default='pending', max_length=20)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5)),
                ('loan_level', models.CharField(default='basic', max_length=10)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cycle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal_portion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_portion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('is_early', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
